automation:
  - alias: Dynamic Hourly Irrigation Adjustment
    trigger:
      - platform: time_pattern
        hours: "/1"
    condition:
      - condition: numeric_state
        entity_id: sensor.evapotranspiration_et
        above: 0.1
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.linktap_valve
        data:
          duration: "{{ states('sensor.irrigation_duration') | int }}"